# $Id$
# $TSUKUBA_Release: Omni Compiler Version 0.9.1 $
# $TSUKUBA_Copyright:
#  Copyright (C) 2010-2014 University of Tsukuba, 
#  	      2012-2014  University of Tsukuba and Riken AICS
#  
#  This software is free software; you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License version
#  2.1 published by the Free Software Foundation.
#  
#  Please check the Copyright and License information in the files named
#  COPYRIGHT and LICENSE under the top  directory of the Omni Compiler
#  Software release kit.
#  
#  * The specification of XcalableMP has been designed by the XcalableMP
#    Specification Working Group (http://www.xcalablemp.org/).
#  
#  * The development of this software was partially supported by "Seamless and
#    Highly-productive Parallel Programming Environment for
#    High-performance computing" project funded by Ministry of Education,
#    Culture, Sports, Science and Technology, Japan.
#  $
SHELL		= /bin/sh
EXEC		= /bin/sh -c
CC		= omcc
CFLAGS		= -O

PROGRAMS	= atomic001 atomic002 atomic003 atomic004 \
		  atomic005 atomic006 atomic007 atomic008 \
		  atomic009 atomic010 atomic011 atomic012
OBJS		= atomic001.o atomic002.o atomic003.o atomic004.o \
		  atomic005.o atomic006.o atomic007.o atomic008.o \
		  atomic009.o atomic010.o atomic011.o atomic012.o
SRCS		= atomic001.c atomic002.c atomic003.c atomic004.c \
		  atomic005.c atomic006.c atomic007.c atomic008.c \
		  atomic009.c atomic010.c atomic011.c atomic012.c


all:	${PROGRAMS}

clean:
	rm -f ${PROGRAMS} ${OBJS} *~

test:	${PROGRAMS}
	@for prog in ${PROGRAMS}; do	\
	  echo "run : $$prog";		\
	  $(EXEC) ./$$prog;		\
	done
