!! This file is automatically generated by xmp_lib_coarray_alloc.h.sh

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc0d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc0d_i2(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer(2), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_i4(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_i8(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_l2(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        logical(2), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_l4(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        logical(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_l8(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        logical(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_r4(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        real(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_r8(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        real(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_z8(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        complex(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_z16(descptr, var, count,          &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        complex(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_alloc0d_cn(descptr, var, count,           &
     &   element, tag, rank)
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        character(element), pointer, intent(out) :: var
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc1d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc1d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer(2), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        logical(2), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        logical(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        logical(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        real(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        real(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        complex(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        complex(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_alloc1d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        character(element), pointer, intent(out) :: var(:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc2d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc2d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer(2), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        logical(2), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        logical(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        logical(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        real(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        real(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        complex(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        complex(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_alloc2d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        character(element), pointer, intent(out) :: var(:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc3d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc3d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer(2), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        logical(2), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        logical(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        logical(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        real(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        real(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        complex(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        complex(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc3d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        character(element), pointer, intent(out) :: var(:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc4d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc4d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer(2), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        logical(2), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        logical(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        logical(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        real(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        real(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        complex(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        complex(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc4d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        character(element), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc5d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc5d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer(2), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        logical(2), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        logical(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        logical(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        real(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        real(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        complex(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        complex(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc5d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        character(element), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc6d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc6d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer(2), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        logical(2), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        logical(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        logical(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        real(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        real(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        complex(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        complex(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc6d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        character(element), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_alloc7d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_alloc7d_i2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        integer(2), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_i4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        integer(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_i8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        integer(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_l2(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        logical(2), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_l4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        logical(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_l8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        logical(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_r4(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        real(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_r8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        real(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_z8(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        complex(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_z16(descptr, var, count,          &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        complex(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_alloc7d_cn(descptr, var, count,           &
     &   element, tag, rank                                             &
     &   , lb1, ub1                                                     &
     &   , lb2, ub2                                                     &
     &   , lb3, ub3                                                     &
     &   , lb4, ub4                                                     &
     &   , lb5, ub5                                                     &
     &   , lb6, ub6                                                     &
     &   , lb7, ub7                                                     &
     &   )
        integer(8), intent(in) :: descptr
        integer(8), intent(in) :: tag
        integer, intent(in) :: count, element, rank
        integer, intent(in) :: lb1, ub1
        integer, intent(in) :: lb2, ub2
        integer, intent(in) :: lb3, ub3
        integer, intent(in) :: lb4, ub4
        integer, intent(in) :: lb5, ub5
        integer, intent(in) :: lb6, ub6
        integer, intent(in) :: lb7, ub7
        character(element), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc0d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc0d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var
      end subroutine

      subroutine xmpf_coarray_dealloc0d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc1d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc1d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:)
      end subroutine

      subroutine xmpf_coarray_dealloc1d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc2d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc2d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc2d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc3d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc3d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc3d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc4d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc4d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc4d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc5d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc5d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc5d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:,:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc6d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc6d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc6d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:,:,:,:,:,:)
      end subroutine

      end interface

!-----------------------------------------------------------------------
      interface xmpf_coarray_dealloc7d
!-----------------------------------------------------------------------
!!!  real(kind=16) is not supported in XMP/F
!!!  complex(kind=16) (32bytes) is not supported in XMP/F

      subroutine xmpf_coarray_dealloc7d_i2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(2), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_i4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_i8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        integer(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_l2(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(2), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_l4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_l8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        logical(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_r4(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_r8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        real(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_z8(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(4), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_z16(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        complex(8), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      subroutine xmpf_coarray_dealloc7d_cn(descptr, var, tag)
        integer(8), intent(in) :: descptr, tag
        character(*), pointer, intent(out) :: var(:,:,:,:,:,:,:)
      end subroutine

      end interface

