/* 
 * $TSUKUBA_Release: Omni OpenMP Compiler 3 $
 * $TSUKUBA_Copyright:
 *  PLEASE DESCRIBE LICENSE AGREEMENT HERE
 *  $
 */
/*
 * This class is generated by ./buildutils/genMachineDepJava
 */
package exc.util;

public interface MachineDepConst
{
    public static final int SIZEOF_DOUBLE = 8;
    public static final int SIZEOF_FLOAT = 4;
    public static final int SIZEOF_LONG_DOUBLE = 16;
    public static final int SIZEOF_UNSIGNED_CHAR = 1;
    public static final int SIZEOF_UNSIGNED_INT = 4;
    public static final int SIZEOF_UNSIGNED_LONG = 8;
    public static final int SIZEOF_UNSIGNED_LONG_LONG = 8;
    public static final int SIZEOF_UNSIGNED_SHORT = 2;
    public static final int SIZEOF_VOID_P = 8;
    public static final int SIZEOF__BOOL = 1;
}

