/* This file is generated automatically by c-exprcode.pl */

#ifndef _C_EXPRCODE_H_
#define _C_EXPRCODE_H_

typedef enum {

	EC_UNDEF                        =   0,
	EC_CHAR_CONST                   =   1,
	EC_STRING_CONST                 =   2,
	EC_NUMBER_CONST                 =   3,
	EC_DEFAULT_LABEL                =   4,
	EC_ELLIPSIS                     =   5,
	EC_IDENT                        =   6,
	EC_NULL_NODE                    =   7,
	EC_EXT_DEFS                     =   8,
	EC_FUNC_DEF                     =   9,
	EC_DECL                         =  10,
	EC_DATA_DEF                     =  11,
	EC_INIT                         =  12,
	EC_INITIALIZER                  =  13,
	EC_INITIALIZERS                 =  14,
	EC_INIT_DECL                    =  15,
	EC_INIT_DECLS                   =  16,
	EC_DESIGNATORS                  =  17,
	EC_ARRAY_DESIGNATOR             =  18,
	EC_DECLARATOR                   =  19,
	EC_STRUCT_TYPE                  =  20,
	EC_UNION_TYPE                   =  21,
	EC_ENUM_TYPE                    =  22,
	EC_MEMBERS                      =  23,
	EC_MEMBER_DECL                  =  24,
	EC_MEMBER_DECLS                 =  25,
	EC_MEMBER_DECLARATOR            =  26,
	EC_ENUMERATORS                  =  27,
	EC_GCC_LABEL_DECLS              =  28,
	EC_COMPOUND_LITERAL             =  29,
	EC_PARAMS                       =  30,
	EC_IDENTS                       =  31,
	EC_GCC_LABEL_IDENTS             =  32,
	EC_STMTS_AND_DECLS              =  33,
	EC_COMP_STMT                    =  34,
	EC_EXPRS                        =  35,
	EC_GCC_COMP_STMT_EXPR           =  36,
	EC_EXPR_STMT                    =  37,
	EC_IF_STMT                      =  38,
	EC_WHILE_STMT                   =  39,
	EC_DO_STMT                      =  40,
	EC_FOR_STMT                     =  41,
	EC_SWITCH_STMT                  =  42,
	EC_BREAK_STMT                   =  43,
	EC_CONTINUE_STMT                =  44,
	EC_RETURN_STMT                  =  45,
	EC_GOTO_STMT                    =  46,
	EC_CASE_LABEL                   =  47,
	EC_LABEL                        =  48,
	EC_LABELS                       =  49,
	EC_FUNCTION_CALL                =  50,
	EC_TYPE_DESC                    =  51,
	EC_BRACED_EXPR                  =  52,
	EC_UNARY_MINUS                  =  53,
	EC_BIT_NOT                      =  54,
	EC_POINTER_REF                  =  55,
	EC_ADDR_OF                      =  56,
	EC_PRE_INCR                     =  57,
	EC_PRE_DECR                     =  58,
	EC_LOG_NOT                      =  59,
	EC_SIZE_OF                      =  60,
	EC_CAST                         =  61,
	EC_POST_INCR                    =  62,
	EC_POST_DECR                    =  63,
	EC_LSHIFT                       =  64,
	EC_RSHIFT                       =  65,
	EC_PLUS                         =  66,
	EC_MINUS                        =  67,
	EC_MUL                          =  68,
	EC_DIV                          =  69,
	EC_MOD                          =  70,
	EC_ARITH_EQ                     =  71,
	EC_ARITH_NE                     =  72,
	EC_ARITH_GE                     =  73,
	EC_ARITH_GT                     =  74,
	EC_ARITH_LE                     =  75,
	EC_ARITH_LT                     =  76,
	EC_LOG_AND                      =  77,
	EC_LOG_OR                       =  78,
	EC_BIT_AND                      =  79,
	EC_BIT_OR                       =  80,
	EC_BIT_XOR                      =  81,
	EC_ASSIGN                       =  82,
	EC_ASSIGN_PLUS                  =  83,
	EC_ASSIGN_MINUS                 =  84,
	EC_ASSIGN_MUL                   =  85,
	EC_ASSIGN_DIV                   =  86,
	EC_ASSIGN_MOD                   =  87,
	EC_ASSIGN_LSHIFT                =  88,
	EC_ASSIGN_RSHIFT                =  89,
	EC_ASSIGN_BIT_AND               =  90,
	EC_ASSIGN_BIT_OR                =  91,
	EC_ASSIGN_BIT_XOR               =  92,
	EC_CONDEXPR                     =  93,
	EC_POINTS_AT                    =  94,
	EC_ARRAY_REF                    =  95,
	EC_ARRAY_DIMENSION              =  96,
	EC_MEMBER_REF                   =  97,
	EC_FLEXIBLE_STAR                =  98,
	EC_XMP_COARRAY_DECLARATION      =  99,
	EC_XMP_COARRAY_DECLARATIONS     = 100,
	EC_XMP_COARRAY_DIM_DEFS         = 101,
	EC_XMP_COARRAY_DIMENSIONS       = 102,
	EC_XMP_COARRAY_REF              = 103,
	EC_XMP_CRITICAL                 = 104,
	EC_GCC_EXTENSION                = 105,
	EC_GCC_LABEL_ADDR               = 106,
	EC_GCC_ALIGN_OF                 = 107,
	EC_GCC_TYPEOF                   = 108,
	EC_GCC_REALPART                 = 109,
	EC_GCC_IMAGPART                 = 110,
	EC_GCC_BLTIN_VA_ARG             = 111,
	EC_GCC_BLTIN_OFFSET_OF          = 112,
	EC_GCC_BLTIN_TYPES_COMPATIBLE_P = 113,
	EC_GCC_OFS_MEMBER_REF           = 114,
	EC_GCC_OFS_ARRAY_REF            = 115,
	EC_GCC_ATTRS                    = 116,
	EC_GCC_ATTR_ARG                 = 117,
	EC_GCC_ATTR_ARGS                = 118,
	EC_GCC_ASM_STMT                 = 119,
	EC_GCC_ASM_EXPR                 = 120,
	EC_GCC_ASM_ARG                  = 121,
	EC_GCC_ASM_OPE                  = 122,
	EC_GCC_ASM_OPES                 = 123,
	EC_GCC_ASM_CLOBS                = 124,
	EC_DIRECTIVE                    = 125,
	EC_STRINGS                      = 126,
	EC_DECL_SPECS                   = 127,
	EC_LDECLARATOR                  = 128,
	EC_DATA_DECL                    = 129,
	EC_DATA_DECLS                   = 130,
	EC_ARRAY_DECL                   = 131,
	EC_COARRAY_DECL                 = 132,
	EC_POINTER_DECL                 = 133,
	EC_PARAM                        = 134,
	EC_TYPENAME                     = 135,
	EC_SCSPEC                       = 136,
	EC_TYPESPEC                     = 137,
	EC_ERROR_NODE                   = 138,
	EC_TYPEQUAL                     = 139,
	EC_PRAGMA_PACK                  = 140,
	EC_XMP_DESC_OF                  = 141,
    EC_END = 142

} CExprCodeEnum;

typedef struct {
    CExprTypeEnum   ec_type;
    const char      *ec_name;
    const char      *ec_opeName;
} CExprCodeInfo;

extern const CExprCodeInfo s_CExprCodeInfos[EC_END];

#endif /* _C_EXPRCODE_H_ */

